//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRUpdates.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int FriendId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int FriendShipStatusId { get; set; }
    
        public virtual Lkp_FriendShipStatus Lkp_FriendShipStatus { get; set; }
        public virtual User User { get; set; }
    }
}
