//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRUpdates.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LatestTechnology
    {
        public int Id { get; set; }
        public int CommunityId { get; set; }
        public int UserId { get; set; }
        public int SubCommunityId { get; set; }
        public string Subject { get; set; }
        public string Tag { get; set; }
        public string Topic { get; set; }
        public string Content { get; set; }
        public string Url { get; set; }
        public string VideoUrl { get; set; }
        public string FilePath { get; set; }
        public bool IsActive { get; set; }
    
        public virtual User User { get; set; }
    }
}
