//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRUpdates.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class proworldzdbNEWEntities : DbContext
    {
        public proworldzdbNEWEntities()
            : base("name=proworldzdbNEWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<Community> Communities { get; set; }
        public DbSet<ContactU> ContactUs { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Degree> Degrees { get; set; }
        public DbSet<Friend> Friends { get; set; }
        public DbSet<IndustryType> IndustryTypes { get; set; }
        public DbSet<LatestTechnology> LatestTechnologies { get; set; }
        public DbSet<LatestTutorial> LatestTutorials { get; set; }
        public DbSet<Lkp_FriendShipStatus> Lkp_FriendShipStatus { get; set; }
        public DbSet<MasterContent> MasterContents { get; set; }
        public DbSet<MasterFilePath> MasterFilePaths { get; set; }
        public DbSet<MasterModuleTypeData> MasterModuleTypeDatas { get; set; }
        public DbSet<MasterUrl> MasterUrls { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<UserGeneralInfomation> UserGeneralInfomations { get; set; }
        public DbSet<UserPersonalInfomation> UserPersonalInfomations { get; set; }
        public DbSet<UserPostComment> UserPostComments { get; set; }
        public DbSet<UserPost> UserPosts { get; set; }
        public DbSet<UserProfessionalQualification> UserProfessionalQualifications { get; set; }
        public DbSet<UserQualification> UserQualifications { get; set; }
        public DbSet<UserResume> UserResumes { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
        public DbSet<UserVideo> UserVideos { get; set; }
    }
}
