//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRUpdates.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Friends = new HashSet<Friend>();
            this.LatestTechnologies = new HashSet<LatestTechnology>();
            this.LatestTutorials = new HashSet<LatestTutorial>();
            this.UserGeneralInfomations = new HashSet<UserGeneralInfomation>();
            this.UserPersonalInfomations = new HashSet<UserPersonalInfomation>();
            this.UserPostComments = new HashSet<UserPostComment>();
            this.UserPosts = new HashSet<UserPost>();
            this.UserProfessionalQualifications = new HashSet<UserProfessionalQualification>();
            this.UserQualifications = new HashSet<UserQualification>();
            this.UserResumes = new HashSet<UserResume>();
            this.UserVideos = new HashSet<UserVideo>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int UserTypeId { get; set; }
        public System.DateTime DOB { get; set; }
        public string Gender { get; set; }
        public int CommunityId { get; set; }
        public int SubCommunityId { get; set; }
        public string CommunityName { get; set; }
        public string SubCommunityName { get; set; }
        public int CityId { get; set; }
        public int StateId { get; set; }
        public int CountryId { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsOnline { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<Friend> Friends { get; set; }
        public virtual ICollection<LatestTechnology> LatestTechnologies { get; set; }
        public virtual ICollection<LatestTutorial> LatestTutorials { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<UserGeneralInfomation> UserGeneralInfomations { get; set; }
        public virtual ICollection<UserPersonalInfomation> UserPersonalInfomations { get; set; }
        public virtual ICollection<UserPostComment> UserPostComments { get; set; }
        public virtual ICollection<UserPost> UserPosts { get; set; }
        public virtual ICollection<UserProfessionalQualification> UserProfessionalQualifications { get; set; }
        public virtual ICollection<UserQualification> UserQualifications { get; set; }
        public virtual ICollection<UserResume> UserResumes { get; set; }
        public virtual ICollection<UserVideo> UserVideos { get; set; }
    }
}
