//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRUpdates.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPost
    {
        public UserPost()
        {
            this.UserPostComments = new HashSet<UserPostComment>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Subject { get; set; }
        public string Post { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public int PostType { get; set; }
    
        public virtual ICollection<UserPostComment> UserPostComments { get; set; }
        public virtual User User { get; set; }
    }
}
